### ISSUE TITLE
java.lang.NullPointerException in com.kuxhausen.huemore.net.hue.HubConnection.initializeConnection

### ISSUE THREAD

**Issue by ekux44** [ekux44/HueMore#63]
Reported on
LampShade: 2.8.10
Android: 4.2
Device: PadFone

    java.lang.NullPointerException
    at com.kuxhausen.huemore.net.hue.HubConnection.initializeConnection(HubConnection.java:114)
    at com.kuxhausen.huemore.net.hue.HubConnection.updateConfiguration(HubConnection.java:339)
    at com.kuxhausen.huemore.net.hue.ui.ConfigureHubDialogFragment$1.onClick(ConfigureHubDialogFragment.java:64)
    at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:170)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5086)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by ekux44** [comment]
Can't reproduce and hasn't been reported in any version of LampShade within the past 6 months.
