### ISSUE TITLE
java.lang.NullPointerException in com.kuxhausen.huemore.net.hue.api.StateSuccessListener.onResponse

### ISSUE THREAD

**Issue by ekux44** [ekux44/HueMore#64]
Reported on
LampShade: 2.8.10
Android: 4.4
Device: Nexus 4

    java.lang.NullPointerException
    at com.kuxhausen.huemore.net.hue.api.StateSuccessListener.onResponse(StateSuccessListener.java:21)
    at com.kuxhausen.huemore.net.hue.api.StateSuccessListener.onResponse(StateSuccessListener.java:7)
    at com.kuxhausen.huemore.net.hue.api.GsonRequest.deliverResponse(GsonRequest.java:83)
    at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5052)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by ekux44** [comment]
Can't reproduce and hasn't been reported in any version of LampShade within the past 6 months
