### ISSUE TITLE
java.lang.NullPointerException in com.kuxhausen.huemore.automation.EditActivity.getSerializedByNamePreview

### ISSUE THREAD

**Issue by ekux44** [ekux44/HueMore#65]
Reported on
LampShade: 2.8.10
Android: 4.4
Device: Nexus 5

    java.lang.NullPointerException
    at com.kuxhausen.huemore.automation.EditActivity.getSerializedByNamePreview(EditActivity.java:205)
    at com.kuxhausen.huemore.automation.EditActivity.onClick(EditActivity.java:158)
    at android.view.View.performClick(View.java:4438)
    at android.view.View$PerformClick.run(View.java:18422)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5001)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by ekux44** [comment]
Can't reproduce and has not been reported in any version of LampShade within the past 6 months.
