### ISSUE TITLE
java.lang.IllegalArgumentException in com.kuxhausen.huemore.net.BrightnessManager.setState

### ISSUE THREAD

**Issue by ekux44** [ekux44/HueMore#68]
LampShade 2.9.1, 2.9.2
Android 4.2, 4.4

```
java.lang.IllegalArgumentException
at com.kuxhausen.huemore.net.BrightnessManager.setState(BrightnessManager.java:56)
at com.kuxhausen.huemore.net.MoodPlayer.tick(MoodPlayer.java:131)
at com.kuxhausen.huemore.net.LifecycleController$InternalClock.onTick(LifecycleController.java:168)
at alt.android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:128)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:152)
at android.app.ActivityThread.main(ActivityThread.java:5132)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ekux44** [comment]
Confirmed still an issue, though the line number changed.

LampShade version: 79, 80
Android version: 4.2, 4.4, 5.0, 5.1
Devices; mx4, Xperia Z2 (D6503), Nexus 5 (hammerhead), MeMO Pad HD 7 (ME173X) (ME173X), Galaxy Note3 (hlte)

    java.lang.IllegalArgumentException
    	at com.kuxhausen.huemore.net.BrightnessManager.setState(BrightnessManager.java:59)
    	at com.kuxhausen.huemore.net.MoodPlayer.tick(MoodPlayer.java:139)
    	at com.kuxhausen.huemore.net.LifecycleController$InternalClock.onTick(LifecycleController.java:168)
    	at alt.android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:128)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loop(Looper.java:153)
    	at android.app.ActivityThread.main(ActivityThread.java:5299)
    	at java.lang.reflect.Method.invokeNative(Native Method)
    	at java.lang.reflect.Method.invoke(Method.java:511)
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
    	at dalvik.system.NativeStart.main(Native Method)
