### ISSUE TITLE
ava.lang.NumberFormatException: Invalid float: ",4"

### ISSUE THREAD

**Issue by ekux44** [ekux44/HueMore#87]
LampShade Version: 3.1.0
Android Version: 4.0, 4.1, 4.2, 4.3, 4.4, 5.0
Devices: phones and tablets in locales with different number formatting rules than the java default of en-US

    at java.lang.StringToReal.invalidReal(StringToReal.java:63)
    at java.lang.StringToReal.parseFloat(StringToReal.java:310)
    at java.lang.Float.parseFloat(Float.java:300)
    at com.kuxhausen.huemore.editmood.EditStateDialogFragment.getTransitionTime(EditStateDialogFragment.java:233)
    at com.kuxhausen.huemore.editmood.EditStateDialogFragment.onClick(EditStateDialogFragment.java:246)
    at android.view.View.performClick(View.java:4438)
    at android.view.View$PerformClick.run(View.java:18422)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5001)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by ekux44** [comment]
Fixed in f049195c7365f85be359be0786e57aa54f155eba
